# Generated by Django 5.0.4 on 2025-01-07 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='special_code',
            field=models.CharField(editable=False, max_length=5, unique=True),
        ),
    ]
