# Generated by Django 5.0.4 on 2025-01-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_user_special_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='register',
            field=models.CharField(default=123, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
